apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment 
  labels:
    app: AuthService 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthService
  template:
    metadata:
      labels:
        app: AuthService
    spec:
      containers:
      - name: authservice
        image: pmscr.azurecr.io/authmicroserviceimage:latest
        resources:
        env:
           - name: ConnectionString
             value: Server = "tcp:authpension.database.windows.net,1433; Initial Catalog = MSONEPensionDb; Persist Security Info = False; User ID = pension; Password = Subhadip@1202; MultipleActiveResultSets = False; Encrypt = True; TrustServerCertificate = False; Connection Timeout = 30;"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: pensionmanagementsvcsecret  
---


apiVersion: v1
kind: Service
metadata:
  name: authservicesvc
spec:
  type: LoadBalancer
  selector:
    app: AuthService
  ports:
  - port: 80
